# Generated by Django 3.2.4 on 2021-08-17 08:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0007_auto_20201211_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireInsuranceDetails',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField()),
                ('basic_premium', models.FloatField()),
                ('compensation_fund_levy', models.FloatField()),
                ('training_levy', models.FloatField()),
                ('stamp_duty', models.FloatField()),
                ('gross_premium', models.FloatField()),
                ('commission', models.FloatField()),
                ('withholding_tax', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='firepolicy',
            name='policy_period_end_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 17, 8, 47, 21, 120929, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firepolicy',
            name='policy_period_start_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 17, 8, 47, 28, 433767, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firepolicy',
            name='transaction_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='firepolicy',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('R', 'Renewal'), ('A', 'Additional'), ('E', 'Extension'), ('C', 'Credit Note')], default='N', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='firepolicy',
            name='fire_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fire.fireinsurancedetails'),
        ),
    ]
