# Generated by Django 3.2.4 on 2021-08-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0010_alter_firepolicy_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firepolicy',
            name='policy_period_end_date',
        ),
        migrations.RemoveField(
            model_name='firepolicy',
            name='policy_period_start_date',
        ),
    ]
