# Generated by Django 3.2.4 on 2021-08-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0011_auto_20210817_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firepolicy',
            name='fire_details',
        ),
    ]
