# Generated by Django 3.0.8 on 2020-07-23 13:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancecompany', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancecompany',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='mobile_number',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='physical_address',
            field=models.CharField(default='default-location', max_length=250),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='telephone_number',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='postal_address',
            field=models.CharField(max_length=70),
        ),
    ]
