# Generated by Django 3.0.8 on 2020-07-23 13:10

from django.db import migrations
from ..helpers.prepopulate_db import migrate_data


class Migration(migrations.Migration):

    dependencies = [
        ('insurancecompany', '0002_auto_20200723_1642'),
    ]

    operations = [
        migrations.RunPython(migrate_data)
    ]
