# Generated by Django 3.2.24 on 2024-09-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancecompany', '0005_historicalinsurancecompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalinsurancecompany',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical insurance company', 'verbose_name_plural': 'historical insurance companys'},
        ),
        migrations.AlterField(
            model_name='historicalinsurancecompany',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
