# Generated by Django 3.1.4 on 2020-12-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burglary', '0005_auto_20201111_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burglarypolicy',
            name='properties',
        ),
        migrations.AddField(
            model_name='burglarypolicy',
            name='properties',
            field=models.ManyToManyField(to='burglary.Property'),
        ),
    ]
