# Generated by Django 3.1.4 on 2020-12-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
        ('burglary', '0006_auto_20201208_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='burglarypolicy',
            name='additional_premiums',
            field=models.ManyToManyField(to='policies.AdditionalPremium'),
        ),
    ]
