# Generated by Django 3.2.4 on 2021-08-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burglary', '0009_historicalburglarypolicy_historicalproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burglarypolicy',
            name='debit_note_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalburglarypolicy',
            name='debit_note_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
