# Generated by Django 3.2 on 2021-08-25 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_auto_20210614_1435'),
        ('burglary', '0010_auto_20210818_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='burglarypolicy',
            name='corporate_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_client_burglary_policy', to='client.corporateclient'),
        ),
        migrations.AddField(
            model_name='historicalburglarypolicy',
            name='corporate_client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='client.corporateclient'),
        ),
    ]
