# Generated by Django 3.2 on 2021-08-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burglary', '0011_auto_20210825_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='burglarypolicy',
            old_name='properties',
            new_name='burglary_properties',
        ),
    ]
