# Generated by Django 3.2 on 2021-08-31 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politicalViolence', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polticalviolence',
            old_name='burglary_properties',
            new_name='political_violence_properties',
        ),
    ]
