# Generated by Django 3.2 on 2021-08-31 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurancecompany', '0005_historicalinsurancecompany'),
        ('agency', '0006_auto_20210309_0851'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policies', '0001_initial'),
        ('client', '0017_auto_20210614_1435'),
        ('politicalViolence', '0002_rename_burglary_properties_polticalviolence_political_violence_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalViolence',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debit_note_no', models.CharField(blank=True, max_length=50, null=True)),
                ('policy_no', models.CharField(max_length=50)),
                ('transaction_date', models.DateField(max_length=8)),
                ('start_date', models.DateField(max_length=8)),
                ('end_date', models.DateField(max_length=8)),
                ('renewal_date', models.DateField(blank=True, max_length=8, null=True)),
                ('commission_rate', models.FloatField(blank=True, null=True)),
                ('minimum_premium_amount', models.FloatField(blank=True, null=True)),
                ('withholding_tax', models.FloatField(blank=True, null=True)),
                ('policy_commission_rate', models.FloatField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('NEW', 'New'), ('RENEW', 'Renewal'), ('ADD', 'Additional'), ('EXT', 'Extension'), ('DEL', 'Deletion'), ('CN', 'Credit Note')], default='NEW', max_length=5)),
                ('premium_type', models.CharField(choices=[('BASIC', 'Basic Premium'), ('POLICY', 'Policy Holder Compensation Fund Levy'), ('STAMPD', 'Stamp Duty'), ('IPHCFLEVY', 'Add IPHCF/Levy'), ('TLEVY', 'Add T/Levy'), ('GROSS', 'Gross premium'), ('COMM', 'Commission'), ('WITH', 'Withholding Tax')], default='BASIC', max_length=15)),
                ('additional_premiums', models.ManyToManyField(to='policies.AdditionalPremium')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicalviolence_politicalviolence_related', to='agency.agency')),
                ('corporate_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='politicalviolence_politicalviolence_related', to='client.corporateclient')),
                ('individual_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='politicalviolence_politicalviolence_related', to='client.individualclient')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicalviolence_politicalviolence_related', to='insurancecompany.insurancecompany')),
                ('political_violence_properties', models.ManyToManyField(to='politicalViolence.Property')),
            ],
            options={
                'unique_together': {('policy_no', 'agency')},
            },
        ),
        migrations.RenameModel(
            old_name='HistoricalPolticalViolence',
            new_name='HistoricalPoliticalViolence',
        ),
        migrations.AlterModelOptions(
            name='historicalpoliticalviolence',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical political violence'},
        ),
        migrations.DeleteModel(
            name='PolticalViolence',
        ),
    ]
