# Generated by Django 3.2.24 on 2024-09-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicalViolence', '0005_auto_20211124_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpoliticalviolence',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical political violence', 'verbose_name_plural': 'historical political violences'},
        ),
        migrations.AlterModelOptions(
            name='historicalproperty',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical property', 'verbose_name_plural': 'historical propertys'},
        ),
        migrations.AlterField(
            model_name='historicalpoliticalviolence',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
