# Generated by Django 3.1.3 on 2020-11-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_groupmedicalins_additional_premiums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmedicalins',
            name='premium_type',
            field=models.CharField(choices=[('BASIC', 'Basic Premium'), ('POLICY', 'Policy Holder Compensation Fund Levy'), ('STAMPD', 'Stamp Duty'), ('IPHCFLEVY', 'Add IPHCF/Levy'), ('TLEVY', 'Add T/Levy'), ('GROSS', 'Gross premium'), ('COMM', 'Commission'), ('WITH', 'Withholding Tax')], default='BASIC', max_length=15),
        ),
    ]
