# Generated by Django 3.1.4 on 2020-12-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
        ('group', '0005_auto_20201111_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmedicalins',
            name='additional_premiums',
        ),
        migrations.AddField(
            model_name='groupmedicalins',
            name='additional_premiums',
            field=models.ManyToManyField(to='policies.AdditionalPremium'),
        ),
    ]
