# Generated by Django 3.2.6 on 2021-12-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_deletion', '0002_auto_20211221_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='policydeletion',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
