# Generated by Django 3.2.6 on 2022-03-02 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0031_auto_20211124_1629'),
        ('insurancecompany', '0005_historicalinsurancecompany'),
        ('agency', '0006_auto_20210309_0851'),
        ('policy_deletion', '0003_policydeletion_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='policydeletion',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_deletion_agency', to='agency.agency'),
        ),
        migrations.AddField(
            model_name='policydeletion',
            name='insurance_class',
            field=models.CharField(choices=[('COMM_GEN', 'Motor Commercial Insurance – GC - Comp'), ('COMM_OWN', 'Motor Commercial Insurance – Own Goods - Comprehensive'), ('COMM_OWN_TPO', 'Motor Commercial Insurance – Own Goods - T.P.O'), ('PRIV_COMP', 'Motor Private Insurance – Comprehensive'), ('PRIV_TPO', 'Motor Private Insurance – T.P.O'), ('PSV_COMP', 'Motor PSV – Comprehensive'), ('PSV_TPO', 'Motor PSV – T.P.O')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='policydeletion',
            name='insurance_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_deletion_insurance_co', to='insurancecompany.insurancecompany'),
        ),
        migrations.AddField(
            model_name='policydeletion',
            name='policy_detail_set',
            field=models.ManyToManyField(to='motor.PolicyTypeSet'),
        ),
        migrations.AlterUniqueTogether(
            name='policydeletion',
            unique_together={('debit_note_no', 'agency')},
        ),
    ]
