# Generated by Django 3.1.4 on 2020-12-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_package', '0006_auto_20201208_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticpackage',
            name='policy_commission_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domesticpackage',
            name='withholding_tax',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
