# Generated by Django 3.2 on 2021-08-25 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_auto_20210614_1435'),
        ('agency', '0006_auto_20210309_0851'),
        ('insurancecompany', '0005_historicalinsurancecompany'),
        ('domestic_package', '0008_alter_domesticpackage_debit_note_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticpackage',
            name='corporate_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domestic_package_domesticpackage_related', to='client.corporateclient'),
        ),
        migrations.AlterField(
            model_name='domesticpackage',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_package_domesticpackage_related', to='agency.agency'),
        ),
        migrations.AlterField(
            model_name='domesticpackage',
            name='individual_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domestic_package_domesticpackage_related', to='client.individualclient'),
        ),
        migrations.AlterField(
            model_name='domesticpackage',
            name='insurance_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_package_domesticpackage_related', to='insurancecompany.insurancecompany'),
        ),
        migrations.AlterField(
            model_name='domesticpackage',
            name='package_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_package_domesticpackage_related', to='domestic_package.domesticpackagedetail'),
        ),
    ]
