# Generated by Django 3.2.6 on 2021-11-26 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_renewal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policyrenewal',
            old_name='policy_number',
            new_name='policy',
        ),
    ]
