# Generated by Django 3.2.6 on 2021-12-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0031_auto_20211124_1629'),
        ('policy_renewal', '0003_alter_policyrenewal_insurance_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrenewal',
            name='additional_benefits',
            field=models.ManyToManyField(to='motor.AdditionalBenefit'),
        ),
        migrations.AlterField(
            model_name='policyrenewal',
            name='insurance_class',
            field=models.CharField(choices=[('COMM_GEN', 'Motor Commercial Insurance – GC - Comp'), ('COMM_OWN', 'Motor Commercial Insurance – Own Goods - Comprehensive'), ('COMM_OWN_TPO', 'Motor Commercial Insurance – Own Goods - T.P.O'), ('PRIV_COMP', 'Motor Private Insurance – Comprehensive'), ('PRIV_TPO', 'Motor Private Insurance – T.P.O'), ('PSV_COMP', 'Motor PSV – Comprehensive'), ('PSV_TPO', 'Motor PSV – T.P.O')], default='COMM_GEN', max_length=50),
        ),
    ]
