# Generated by Django 3.2.6 on 2022-03-02 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0031_auto_20211124_1629'),
        ('insurancecompany', '0005_historicalinsurancecompany'),
        ('agency', '0006_auto_20210309_0851'),
        ('policy_renewal', '0005_auto_20211206_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrenewal',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_renewal_agency', to='agency.agency'),
        ),
        migrations.AddField(
            model_name='policyrenewal',
            name='insurance_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_renewal_insurance_co', to='insurancecompany.insurancecompany'),
        ),
        migrations.AddField(
            model_name='policyrenewal',
            name='policy_detail_set',
            field=models.ManyToManyField(to='motor.PolicyTypeSet'),
        ),
        migrations.AddField(
            model_name='policyrenewal',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='policyrenewal',
            unique_together={('debit_note_no', 'agency')},
        ),
    ]
