# Generated by Django 3.2.6 on 2022-06-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_renewal', '0006_auto_20220302_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyrenewal',
            name='insurance_class',
            field=models.CharField(choices=[('ALL_RISKS', 'All Risks'), ('BIG_BOND', 'Big Bond'), ('BURGLARY', 'Burglary'), ('BUSINESS_COMBINED', 'Business Combined'), ('BUSINESS_INTERRUPTION', 'Business Interruption'), ('CARRIERS_LEGAL_LIABILITY', 'Carriers Legal Liability'), ('COMMERCIAL_BOND', 'Commercial Bond'), ('CONTRACT_BOND', 'Contract Bond'), ('CONTRACTORS_ALL_RISKS', 'Contractors All Risks'), ('COURT_BOND', 'Court Bond'), ('CROP', 'Crop Insurance'), ('CUSTOM_BOND', 'Custom Bond'), ('CYBER_RISK', 'Cyber Risk'), ('DETERIORATION_OF_STOCK', 'Deterioration of Stock'), ('DIRECTORS_OFFICERS_LIABILITY', 'Directors & Officers Liability'), ('DOMESTIC_PACKAGE', 'Domestic Package'), ('ELECTRONIC_EQUIPMENT', 'Electronic Equipment'), ('EMPLOYER_LIABILITY', "Employer's Liability - EL"), ('ERECTION_ALL_RISKS', 'Erection All Risks'), ('FIDELITY_GURANTEE', 'Fidelity Guarantee'), ('FIRE_PERILS', 'Fire & Perils'), ('GOLFERS', 'Golfers'), ('GOODS_IN_TRANSIT', 'Goods in Transit - GIT'), ('GROUP_ACCIDENT', 'Group Accident'), ('GROUP_MEDICAL', 'Group Medical'), ('HOSPITAL_MALPRACTICE', 'Hospital Malpractice'), ('IMMIGRATION_BOND', 'Immigration Bond'), ('IMPORT_BOND', 'Import Bond'), ('INDUSTRIAL_ALL_RISKS', 'Industrial All Risks'), ('INVESTMENT', 'Investment'), ('LAST_EXPENSE', 'Last Expense'), ('LIFE', 'Life'), ('LIVESTOCK', 'Livestock'), ('MACHINERY_BREAKDOWN', 'Machinery Breakdown Insurance'), ('MARINE', 'Marine'), ('MEDICAL', 'Medical'), ('MONEY', 'Money'), ('COMM_GEN', 'Motor Commercial Insurance – General Cartage - Comp'), ('COMM_OWN', 'Motor Commercial Insurance – Own Goods - Comprehensive'), ('COMM_OWN_TPO', 'Motor Commercial Insurance – Own Goods - T.P.O'), ('PRIV_COMP', 'Motor Private Insurance – Comprehensive'), ('PRIV_TPO', 'Motor Private Insurance – T.P.O'), ('PSV_COMP', 'Motor PSV – Comprehensive'), ('PSV_TPO', 'Motor PSV – T.P.O'), ('OCCUPIERS_LIABILITY', 'Occupiers Liability'), ('OWNERS_LIABILITY', 'Owners Liability'), ('PAYMENT_BOND', 'Payment Bond'), ('PENSION', 'Pension'), ('PERFORMANCE_BOND', 'Performance Bond'), ('PERSONAL_ACCIDENT', 'Personal Accident'), ('PLATE_GLASS', 'Plate Glass'), ('POLITICAL_VIOLENCE_TERRORISM', 'Political Violence & Terrorism'), ('PRODCUTS LIABILITY', 'Products Liability'), ('PROFESSIONAL_INDEMNITY', 'Professional Indemnity'), ('PUBLIC_LIABILITY', 'Public Liability Insurance'), ('STOCK', 'Stock'), ('STUDENT_PERSONAL_ACCIDENT', 'Student Personal Accident'), ('TENDER_BOND', 'Tender Bond'), ('TRAVEL', 'Travel'), ('WORK_INJURY_BENEFITS_W', 'Work Injury Benefits ACT - WIBA'), ('WORK_INJURY_BENEFITS_WP', 'Work Injury Benefits ACT - WIBA - Plus')], default='COMM_GEN', max_length=50),
        ),
    ]
