# Generated by Django 3.2.24 on 2024-09-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_renewal', '0007_alter_policyrenewal_insurance_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaladditionalbenefit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical additional benefit', 'verbose_name_plural': 'historical additional benefits'},
        ),
        migrations.AlterField(
            model_name='historicaladditionalbenefit',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
