# Generated by Django 3.1 on 2020-09-17 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0002_auto_20200622_1409'),
        ('client', '0001_initial'),
        ('insurancecompany', '0003_auto_20200723_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalIndemnity',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_no', models.CharField(max_length=50)),
                ('transaction_date', models.DateField(max_length=8)),
                ('start_date', models.DateField(max_length=8)),
                ('end_date', models.DateField(max_length=8)),
                ('renewal_date', models.DateField(blank=True, max_length=8, null=True)),
                ('levies', models.FloatField(blank=True)),
                ('total_premium', models.FloatField(blank=True)),
                ('sum_insured', models.FloatField()),
                ('excess_amount', models.FloatField(blank=True)),
                ('commission_rate', models.FloatField()),
                ('commission_amount', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('NEW', 'New'), ('RENEW', 'Renewal'), ('ADD', 'Additional'), ('EXT', 'Extension'), ('DEL', 'Deletion')], default='NEW', max_length=5)),
                ('specialty_class', models.CharField(choices=[('DENT', 'Dentists'), ('RAD', 'Radiologists'), ('PATH', 'Pathologists'), ('DERM', 'Dermatologists'), ('GEN_PRAC', 'General Practitioners'), ('GYN', 'Gynecologists'), ('SURG', 'Surgeons'), ('DEL', 'Deletion')], default='GEN_PRAC', max_length=10)),
                ('premium_type', models.CharField(choices=[('BASIC', 'Basic Premium'), ('POLICY', 'Policy Holder Compensation Fund Levy'), ('STAMP', 'Stamp Duty'), ('GROSS', 'Gross premium'), ('COMM', 'Commission'), ('WITH', 'Withholding Tax')], default='BASIC', max_length=8)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_indemnity_agency', to='agency.agency')),
                ('individual_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_client_professional_indemnity', to='client.individualclient')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_indemnity_insurance_co', to='insurancecompany.insurancecompany')),
            ],
            options={
                'unique_together': {('policy_no', 'agency')},
            },
        ),
    ]
