# Generated by Django 3.1.3 on 2020-11-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_indemnity', '0002_auto_20200930_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalindemnity',
            name='deleted',
        ),
        migrations.AddField(
            model_name='professionalindemnity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
