# Generated by Django 3.1.6 on 2021-02-23 06:37

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0005_auto_20210208_0806'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motor', '0019_auto_20210216_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorPolicyReceipt',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(db_index=True, max_length=50)),
                ('date', models.DateField(max_length=8)),
                ('transaction_date', models.DateField(max_length=8)),
                ('amount_figures', models.FloatField()),
                ('amount_words', models.CharField(max_length=255)),
                ('issued_by', models.CharField(max_length=255)),
                ('payment_mode', models.CharField(choices=[('M', 'Mpesa'), ('CH', 'Cheque'), ('B', 'Bank Transfer'), ('CA', 'Cash')], max_length=2)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_motorpolicyreceipt_related', to='agency.agency')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_motorpolicyreceipt_related', to='motor.motorpolicy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalMotorPolicyReceipt',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('receipt_number', models.CharField(db_index=True, max_length=50)),
                ('date', models.DateField(max_length=8)),
                ('transaction_date', models.DateField(max_length=8)),
                ('amount_figures', models.FloatField()),
                ('amount_words', models.CharField(max_length=255)),
                ('issued_by', models.CharField(max_length=255)),
                ('payment_mode', models.CharField(choices=[('M', 'Mpesa'), ('CH', 'Cheque'), ('B', 'Bank Transfer'), ('CA', 'Cash')], max_length=2)),
                ('history_change_reason', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), blank=True, null=True, size=None)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('agency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency.agency')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='motor.motorpolicy')),
            ],
            options={
                'verbose_name': 'historical motor policy receipt',
                'db_table': 'history_receipt',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
