# Generated by Django 3.1.7 on 2021-03-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmotorpolicyreceipt',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='motorpolicyreceipt',
            name='issued_by',
        ),
    ]
