# Generated by Django 3.1.7 on 2021-03-01 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipt', '0002_auto_20210301_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmotorpolicyreceipt',
            name='issued_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motorpolicyreceipt',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_motorpolicyreceipt_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
