# Generated by Django 3.2.4 on 2021-08-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0003_auto_20210301_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmotorpolicyreceipt',
            name='date',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmotorpolicyreceipt',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='motorpolicyreceipt',
            name='date',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='motorpolicyreceipt',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
