# Generated by Django 3.2 on 2021-09-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0004_auto_20210809_1523'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalmotorpolicyreceipt',
            table='history_receipt_policy',
        ),
    ]
