# Generated by Django 3.2.24 on 2024-09-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0005_alter_historicalmotorpolicyreceipt_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmotorpolicyreceipt',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical motor policy receipt', 'verbose_name_plural': 'historical motor policy receipts'},
        ),
        migrations.AlterField(
            model_name='historicalmotorpolicyreceipt',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
