# Generated by Django 3.2 on 2021-08-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computerElectronics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computerelectronic',
            old_name='burglary_properties',
            new_name='computer_electronic_properties',
        ),
    ]
