# Generated by Django 3.1.5 on 2021-01-15 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0003_auto_20201105_1431'),
        ('client', '0004_corporateclient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactManager',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('facebook_account', models.URLField(blank=True, null=True)),
                ('twitter_account', models.URLField(blank=True, null=True)),
                ('instagram_account', models.URLField(blank=True, null=True)),
                ('linkedin_account', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('E', 'Exited')], max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer not to disclose')], default='F', max_length=2)),
                ('service_line', models.CharField(max_length=250)),
                ('date_of_birth', models.DateField(blank=True, max_length=8, null=True)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_contactmanager_related', to='agency.agency')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_contactmanager_related', to='client.corporateclient')),
            ],
            options={
                'unique_together': {('email', 'agency'), ('phone_number', 'agency')},
            },
        ),
    ]
