# Generated by Django 3.1.5 on 2021-01-19 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20210118_1646'),
        ('agency', '0003_auto_20201105_1431'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sms', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('email_body', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('email_subject', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('option', models.CharField(choices=[('M', 'Sent to multiple users'), ('S', 'Sent to a single user'), ('A', 'Sent to all users')], default='S', max_length=2)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_message_related', to='agency.agency')),
                ('clients', models.ManyToManyField(to='client.IndividualClient')),
                ('contact_persons', models.ManyToManyField(to='crm.ContactManager')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
