# Generated by Django 3.1.5 on 2021-01-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20210129_1024'),
        ('crm', '0005_auto_20210126_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmanager',
            name='client',
        ),
        migrations.RemoveField(
            model_name='historicalcontactmanager',
            name='client',
        ),
        migrations.AddField(
            model_name='contactmanager',
            name='corporate_clients',
            field=models.ManyToManyField(to='client.CorporateClient'),
        ),
        migrations.AddField(
            model_name='contactmanager',
            name='individual_clients',
            field=models.ManyToManyField(to='client.IndividualClient'),
        ),
    ]
