# Generated by Django 3.2 on 2021-04-12 13:23

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0006_auto_20210129_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_sms', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('whatsapp_response', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('whatsapp_phone_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('option', models.CharField(blank=True, choices=[('M', 'Sent to multiple users'), ('S', 'Sent to a single user')], default='S', max_length=7, null=True)),
                ('sales_agent_assigned', models.ManyToManyField(blank=True, null=True, related_name='crm_whatsappmessages_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalWhatsappMessages',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('whatsapp_sms', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('whatsapp_response', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('whatsapp_phone_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('option', models.CharField(blank=True, choices=[('M', 'Sent to multiple users'), ('S', 'Sent to a single user')], default='S', max_length=7, null=True)),
                ('history_change_reason', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), blank=True, null=True, size=None)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical whatsapp messages',
                'db_table': 'history_whatsapp_message',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
