# Generated by Django 3.2 on 2021-04-12 13:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0007_historicalwhatsappmessages_whatsappmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwhatsappmessages',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 12, 13, 31, 45, 478655, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalwhatsappmessages',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalwhatsappmessages',
            name='sales_agent_assigned',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whatsappmessages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappmessages',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='historicalwhatsappmessages',
            name='id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='whatsappmessages',
            name='id',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='whatsappmessages',
            name='sales_agent_assigned',
        ),
        migrations.AddField(
            model_name='whatsappmessages',
            name='sales_agent_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_whatsappmessages_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
