# Generated by Django 3.2 on 2021-04-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20210412_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessages',
            name='agent_responses',
            field=models.ManyToManyField(blank=True, related_name='_crm_whatsappmessages_agent_responses_+', to='crm.WhatsappMessages'),
        ),
    ]
