# Generated by Django 3.2 on 2021-04-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20210414_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwhatsappmessages',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappmessages',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
