# Generated by Django 3.2.4 on 2021-08-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20210416_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwhatsappmessages',
            name='whatsapp_response',
            field=models.CharField(blank=True, db_index=True, max_length=2156, null=True),
        ),
        migrations.AlterField(
            model_name='historicalwhatsappmessages',
            name='whatsapp_sms',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessages',
            name='whatsapp_response',
            field=models.CharField(blank=True, db_index=True, max_length=2156, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessages',
            name='whatsapp_sms',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
    ]
