# Generated by Django 3.2.4 on 2021-08-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_auto_20210614_1435'),
        ('crm', '0012_auto_20210805_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessages',
            name='corporate_clients',
            field=models.ManyToManyField(to='client.CorporateClient'),
        ),
        migrations.AddField(
            model_name='whatsappmessages',
            name='individual_clients',
            field=models.ManyToManyField(to='client.IndividualClient'),
        ),
        migrations.AlterField(
            model_name='historicalwhatsappmessages',
            name='option',
            field=models.CharField(blank=True, choices=[('M', 'Sent to multiple users'), ('S', 'Sent to a single user'), ('A', 'Sent to all users'), ('AC', 'Sent to all corporate clients'), ('AI', 'Sent to all individual clients'), ('ACP', 'Sent to all contact persons')], default='S', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessages',
            name='option',
            field=models.CharField(blank=True, choices=[('M', 'Sent to multiple users'), ('S', 'Sent to a single user'), ('A', 'Sent to all users'), ('AC', 'Sent to all corporate clients'), ('AI', 'Sent to all individual clients'), ('ACP', 'Sent to all contact persons')], default='S', max_length=7, null=True),
        ),
    ]
