# Generated by Django 3.2.24 on 2024-09-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20210809_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcontactmanager',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical contact manager', 'verbose_name_plural': 'historical contact managers'},
        ),
        migrations.AlterModelOptions(
            name='historicalmessage',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical message', 'verbose_name_plural': 'historical messages'},
        ),
        migrations.AlterModelOptions(
            name='historicalwhatsappmessages',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical whatsapp messages', 'verbose_name_plural': 'historical whatsapp messagess'},
        ),
        migrations.AlterField(
            model_name='historicalcontactmanager',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmessage',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalwhatsappmessages',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
