# Generated by Django 3.0.8 on 2020-07-28 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('insurancecompany', '0003_auto_20200723_1610'),
        ('agency', '0002_auto_20200622_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_no', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('chassel_no', models.CharField(max_length=50)),
                ('engine_no', models.CharField(max_length=50)),
                ('seating_capacity', models.IntegerField()),
                ('cc', models.BigIntegerField()),
                ('tonnage', models.BigIntegerField()),
                ('year_of_manufacture', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MotorPolicy',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debit_note_no', models.CharField(max_length=50)),
                ('policy_no', models.CharField(max_length=50)),
                ('transaction_date', models.DateField(max_length=8)),
                ('start_date', models.DateField(max_length=8)),
                ('end_date', models.DateField(max_length=8)),
                ('renewal_date', models.DateField(blank=True, max_length=8, null=True)),
                ('value', models.FloatField()),
                ('insurance_class', models.CharField(choices=[('COMM_GEN', 'Motor Commercial Insurance – General Cartage'), ('COMM_OWN', 'Motor Commercial Insurance – Own Goods'), ('PRIV_COMP', 'Motor Private Insurance – Comprehensive'), ('PRIV_TPO', 'Motor Private Insurance – T.P.O'), ('PSV_COMP', 'Motor PSV – Comprehensive'), ('PSV_TPO', 'Motor PSV – T.P.O')], default='COMM_GEN', max_length=10)),
                ('transaction_type', models.CharField(choices=[('NEW', 'New'), ('RENEW', 'Renewal'), ('ADD', 'Additional'), ('EXT', 'Extension'), ('DEL', 'Deletion')], default='NEW', max_length=5)),
                ('premium_type', models.CharField(choices=[('BASIC', 'Basic Premium'), ('POLICY', 'Policy Holder Compensation Fund Levy'), ('STAMP', 'Stamp Duty'), ('GROSS', 'Gross premium'), ('COMM', 'Commission'), ('WITH', 'Withholding Tax')], default='BASIC', max_length=8)),
                ('additional_benefit', models.CharField(choices=[('COURT', 'Courtesy car'), ('EXCESS', 'Excess Protection'), ('WIND', 'Windscreen extension'), ('MED', 'Medical expenses')], default='COURT', max_length=8)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motor_policy_agency', to='agency.Agency')),
                ('individual_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_client_motor_policy', to='client.IndividualClient')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motor_policy_insurance_co', to='insurancecompany.InsuranceCompany')),
                ('vehicle_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motor_policy_vehicle', to='motor.VehicleDetails')),
            ],
            options={
                'unique_together': {('debit_note_no', 'agency'), ('policy_no', 'agency')},
            },
        ),
    ]
