# Generated by Django 3.1 on 2020-11-05 08:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0002_auto_20200930_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalBenefit',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('benefit', models.CharField(choices=[('COURT', 'Courtesy car'), ('EXCESS', 'Excess Protection'), ('WIND', 'Windscreen extension'), ('MED', 'Medical expenses')], default='COURT', max_length=8)),
                ('commission_rate', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='motorpolicy',
            name='additional_benefit',
        ),
        migrations.AddField(
            model_name='motorpolicy',
            name='additional_benefits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None),
        ),
    ]
