# Generated by Django 3.1.3 on 2020-11-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0005_motorpolicy_minimum_premium_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalbenefit',
            name='minimum_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
