# Generated by Django 3.1.3 on 2020-11-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0006_additionalbenefit_minimum_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalbenefit',
            name='benefit',
            field=models.CharField(choices=[('COURT', 'Courtesy car'), ('EXCESS', 'Excess Protection'), ('WIND', 'Windscreen extension'), ('MED', 'Medical expenses'), ('POLITICAL', 'Political violence and Terrorism cover')], default='COURT', max_length=15),
        ),
    ]
