# Generated by Django 3.1.3 on 2020-11-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0009_auto_20201111_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorpolicy',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
