# Generated by Django 3.1.6 on 2021-02-08 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_auto_20210208_0806'),
        ('motor', '0016_auto_20210208_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalvehicledetails',
            old_name='chassel_no',
            new_name='chassis_no',
        ),
        migrations.RenameField(
            model_name='vehicledetails',
            old_name='chassel_no',
            new_name='chassis_no',
        ),
        migrations.RemoveField(
            model_name='historicalmotorpolicy',
            name='vehicle_details',
        ),
        migrations.RemoveField(
            model_name='motorpolicy',
            name='vehicle_details',
        ),
        migrations.AddField(
            model_name='historicalvehicledetails',
            name='agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency.agency'),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motor_vehicledetails_related', to='agency.agency'),
        ),
    ]
