# Generated by Django 3.1.6 on 2021-02-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0017_auto_20210208_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicledetails',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
