# Generated by Django 3.1.6 on 2021-02-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_auto_20210208_0806'),
        ('motor', '0018_auto_20210208_1140'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='motorpolicy',
            unique_together={('debit_note_no', 'agency')},
        ),
    ]
