# Generated by Django 3.2 on 2021-07-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0020_auto_20210309_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmotorpolicy',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motorpolicy',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
