# Generated by Django 3.2.4 on 2021-08-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0023_auto_20210809_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmotorpolicy',
            name='debit_note_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='motorpolicy',
            name='debit_note_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
