# Generated by Django 3.2 on 2021-09-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0024_auto_20210818_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalDetails',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_index', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='motorpolicy',
            name='policy_details',
            field=models.ManyToManyField(to='motor.AdditionalDetails'),
        ),
    ]
