# Generated by Django 3.2 on 2021-09-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0026_rename_additionaldetails_policydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policydetails',
            name='type_index',
        ),
        migrations.CreateModel(
            name='PolicyType',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('fields', models.ManyToManyField(to='motor.PolicyDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='motorpolicy',
            name='policy_details',
            field=models.ManyToManyField(to='motor.PolicyType'),
        ),
    ]
