# Generated by Django 3.2 on 2021-09-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0028_policydetailsset_policytypeset'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorpolicy',
            name='policy_detail_set',
            field=models.ManyToManyField(to='motor.PolicyTypeSet'),
        ),
    ]
