# Generated by Django 3.2.24 on 2024-09-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0032_auto_20220629_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaladditionalbenefit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical additional benefit', 'verbose_name_plural': 'historical additional benefits'},
        ),
        migrations.AlterModelOptions(
            name='historicalmotorpolicy',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical motor policy', 'verbose_name_plural': 'historical motor policys'},
        ),
        migrations.AlterModelOptions(
            name='historicalvehicledetails',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical vehicle details', 'verbose_name_plural': 'historical vehicle detailss'},
        ),
        migrations.AlterField(
            model_name='historicaladditionalbenefit',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmotorpolicy',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalvehicledetails',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
