# Generated by Django 3.2.24 on 2024-09-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractorsRisks', '0003_auto_20211124_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcontractorsrisk',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical contractors risk', 'verbose_name_plural': 'historical contractors risks'},
        ),
        migrations.AlterModelOptions(
            name='historicalproperty',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical property', 'verbose_name_plural': 'historical propertys'},
        ),
        migrations.AlterField(
            model_name='historicalcontractorsrisk',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
