# Generated by Django 3.1 on 2020-09-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInsurance',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inpatient_limit', models.FloatField()),
                ('outpatient_limit', models.FloatField()),
                ('family_size', models.IntegerField(blank=True, db_index=True, null=True)),
                ('dependants', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
