# Generated by Django 3.1 on 2020-10-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalinsurance',
            name='age',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalinsurance',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalinsurance',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
