# Generated by Django 3.1 on 2020-10-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_auto_20201001_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinsurance',
            name='inpatient_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalinsurance',
            name='outpatient_limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
