# Generated by Django 3.2 on 2021-08-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consequentialLoss', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consequentialloss',
            old_name='burglary_properties',
            new_name='consequential_loss_properties',
        ),
    ]
