# Generated by Django 3.1.5 on 2021-01-14 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20201105_1431'),
        ('client', '0002_auto_20201105_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualclient',
            name='facebook_account',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='instagram_account',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='linkedin_account',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='twitter_account',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualclient',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_individualclient_related', to='agency.agency'),
        ),
        migrations.CreateModel(
            name='CorporateClient',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(db_index=True, max_length=50, unique=True)),
                ('postal_address', models.CharField(blank=True, max_length=70, null=True)),
                ('kra_pin', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('town', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('facebook_account', models.URLField(blank=True, null=True)),
                ('twitter_account', models.URLField(blank=True, null=True)),
                ('instagram_account', models.URLField(blank=True, null=True)),
                ('linkedin_account', models.URLField(blank=True, null=True)),
                ('about', models.CharField(blank=True, max_length=250, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_corporateclient_related', to='agency.agency')),
            ],
            options={
                'unique_together': {('email', 'agency'), ('phone_number', 'agency'), ('kra_pin', 'agency')},
            },
        ),
    ]
