# Generated by Django 3.1.5 on 2021-01-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20210114_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateclient',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
