# Generated by Django 3.1.5 on 2021-01-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20201105_1431'),
        ('client', '0004_corporateclient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateclient',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='corporateclient',
            unique_together={('email', 'agency'), ('phone_number', 'agency')},
        ),
    ]
