# Generated by Django 3.1.6 on 2021-02-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20210129_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateclient',
            name='status',
            field=models.CharField(blank=True, choices=[('R', 'Returning'), ('P', 'Potential'), ('Q', 'Qualified'), ('CUS', 'Customer'), ('BF', 'Bad Fit'), ('CA', 'Cancelled'), ('NI', 'Not Interested'), ('L', 'Lost'), ('W', 'Won')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalcorporateclient',
            name='status',
            field=models.CharField(blank=True, choices=[('R', 'Returning'), ('P', 'Potential'), ('Q', 'Qualified'), ('CUS', 'Customer'), ('BF', 'Bad Fit'), ('CA', 'Cancelled'), ('NI', 'Not Interested'), ('L', 'Lost'), ('W', 'Won')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalindividualclient',
            name='status',
            field=models.CharField(blank=True, choices=[('R', 'Returning'), ('P', 'Potential'), ('Q', 'Qualified'), ('CUS', 'Customer'), ('BF', 'Bad Fit'), ('CA', 'Cancelled'), ('NI', 'Not Interested'), ('L', 'Lost'), ('W', 'Won')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='status',
            field=models.CharField(blank=True, choices=[('R', 'Returning'), ('P', 'Potential'), ('Q', 'Qualified'), ('CUS', 'Customer'), ('BF', 'Bad Fit'), ('CA', 'Cancelled'), ('NI', 'Not Interested'), ('L', 'Lost'), ('W', 'Won')], max_length=10, null=True),
        ),
    ]
