# Generated by Django 3.1.6 on 2021-02-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20210209_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateclient',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Prospective'), ('A', 'Active'), ('D', 'Dormant')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcorporateclient',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Prospective'), ('A', 'Active'), ('D', 'Dormant')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindividualclient',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Prospective'), ('A', 'Active'), ('D', 'Dormant')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='individualclient',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Prospective'), ('A', 'Active'), ('D', 'Dormant')], max_length=10, null=True),
        ),
    ]
