# Generated by Django 3.1.7 on 2021-03-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20210222_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateclient',
            name='client_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalcorporateclient',
            name='client_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalindividualclient',
            name='client_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='client_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
