# Generated by Django 3.1.7 on 2021-03-09 05:45

from django.db import migrations



def add_client_number(apps, schema_editor):
    """
        Adds the VehicleDetails object in Client.client_number to the model
    """
    individual_clients = apps.get_model('client', 'IndividualClient')
    corporate_clients = apps.get_model('client', 'CorporateClient')

    i = 1
    for client in individual_clients.objects.all():
        client.client_number = f"CLT-{i:06d}"
        client.save()
        i+=1

    for client in corporate_clients.objects.all():
        client.client_number = f"CLT-{i:06d}"
        client.save()
        i+=1



class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20210309_0844'),
    ]

    operations = [
            migrations.RunPython(add_client_number),
    ]
