# Generated by Django 3.2.4 on 2021-06-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20210614_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateclient',
            name='client_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corporateclient',
            name='email',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcorporateclient',
            name='client_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcorporateclient',
            name='email',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalindividualclient',
            name='client_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindividualclient',
            name='email',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='individualclient',
            name='client_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='individualclient',
            name='email',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
