# Generated by Django 3.2.4 on 2021-06-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20210614_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateclient',
            name='phone_number',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcorporateclient',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalindividualclient',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindividualclient',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindividualclient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer not to disclose')], default='F', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindividualclient',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindividualclient',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindividualclient',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='individualclient',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='individualclient',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='individualclient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer not to disclose')], default='F', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='individualclient',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='individualclient',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='individualclient',
            name='phone_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
