# Generated by Django 3.2.4 on 2021-06-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20210614_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateclient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcorporateclient',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindividualclient',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='individualclient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
