# Generated by Django 3.2.24 on 2024-09-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_auto_20210614_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcorporateclient',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical corporate client', 'verbose_name_plural': 'historical corporate clients'},
        ),
        migrations.AlterModelOptions(
            name='historicalindividualclient',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical individual client', 'verbose_name_plural': 'historical individual clients'},
        ),
        migrations.AlterField(
            model_name='historicalcorporateclient',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalindividualclient',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
