# Generated by Django 3.0.7 on 2020-06-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='image_url',
            field=models.CharField(max_length=250),
        ),
    ]
