# Generated by Django 3.1.5 on 2021-01-23 08:33

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0003_auto_20201105_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAgency',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('office_location', models.CharField(blank=True, max_length=50, null=True)),
                ('box_number', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('postal_code', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('agency_email', models.CharField(db_index=True, max_length=50)),
                ('image_url', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=False)),
                ('history_change_reason', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), blank=True, null=True, size=None)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical agency',
                'db_table': 'history_agency',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
