# Generated by Django 3.1.7 on 2021-03-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_auto_20210208_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='client_number',
            field=models.IntegerField(blank=True, db_index=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalagency',
            name='client_number',
            field=models.IntegerField(blank=True, db_index=True, default=1, null=True),
        ),
    ]
