# Generated by Django 3.2.24 on 2024-09-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_auto_20210309_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalagency',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical agency', 'verbose_name_plural': 'historical agencys'},
        ),
        migrations.AlterField(
            model_name='historicalagency',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
