# Generated by Django 3.2 on 2021-08-31 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronicEquipments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electronicequipment',
            old_name='burglary_properties',
            new_name='electronic_equipment_properties',
        ),
    ]
