# Generated by Django 3.2 on 2021-08-31 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodsTransit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodstransit',
            old_name='burglary_properties',
            new_name='goods_transit_properties',
        ),
    ]
