# Generated by Django 3.1 on 2020-10-06 06:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('insurancecompany', '0003_auto_20200723_1610'),
        ('agency', '0002_auto_20200622_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDetail',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.CharField(db_index=True, max_length=100)),
                ('passport_no', models.BigIntegerField(db_index=True, null=True)),
                ('date_of_travel', models.DateField(max_length=8)),
                ('countries_of_travel', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(db_index=True, max_length=100), blank=True, null=True, size=None)),
                ('modes_of_travel', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(db_index=True, max_length=100), blank=True, null=True, size=None)),
                ('reasons_of_travel', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(db_index=True, max_length=100), blank=True, null=True, size=None)),
                ('next_of_kin', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debit_note_no', models.CharField(blank=True, max_length=50)),
                ('policy_no', models.CharField(max_length=50)),
                ('transaction_date', models.DateField(max_length=8)),
                ('start_date', models.DateField(max_length=8)),
                ('end_date', models.DateField(max_length=8)),
                ('renewal_date', models.DateField(blank=True, max_length=8, null=True)),
                ('commission_rate', models.FloatField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('NEW', 'New'), ('RENEW', 'Renewal'), ('ADD', 'Additional'), ('EXT', 'Extension'), ('DEL', 'Deletion'), ('CN', 'Credit Note')], default='NEW', max_length=5)),
                ('premium_type', models.CharField(choices=[('BASIC', 'Basic Premium'), ('POLICY', 'Policy Holder Compensation Fund Levy'), ('STAMPD', 'Stamp Duty'), ('STAMPL', 'Stamp Levy'), ('GROSS', 'Gross premium'), ('COMM', 'Commission'), ('WITH', 'Withholding Tax')], default='BASIC', max_length=8)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_agency', to='agency.agency')),
                ('individual_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_client_travel', to='client.individualclient')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_insurance_co', to='insurancecompany.insurancecompany')),
                ('travel_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_details', to='travel.traveldetail')),
            ],
            options={
                'unique_together': {('policy_no', 'agency')},
            },
        ),
    ]
