# Generated by Django 3.2 on 2021-08-31 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industrialAllRisks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industrialallrisk',
            old_name='burglary_properties',
            new_name='industrial_all_risks_properties',
        ),
    ]
