# Generated by Django 3.2.6 on 2021-12-16 08:09

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
        ('motor', '0031_auto_20211124_1629'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalBenefit',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('benefit', models.CharField(choices=[('COURT', 'Courtesy car'), ('EXCESS', 'Excess Protection'), ('WIND', 'Windscreen extension'), ('MED', 'Medical expenses'), ('POLITICAL', 'Political violence and Terrorism cover')], default='COURT', max_length=15)),
                ('commission_rate', models.FloatField(null=True)),
                ('minimum_amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyAddition',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debit_note_no', models.CharField(blank=True, max_length=50, null=True)),
                ('policy_no', models.CharField(max_length=50)),
                ('transaction_date', models.DateField(max_length=8)),
                ('start_date', models.DateField(max_length=8)),
                ('end_date', models.DateField(max_length=8)),
                ('renewal_date', models.DateField(blank=True, max_length=8, null=True)),
                ('commission_rate', models.FloatField(blank=True, null=True)),
                ('minimum_premium_amount', models.FloatField(blank=True, null=True)),
                ('withholding_tax', models.FloatField(blank=True, null=True)),
                ('policy_commission_rate', models.FloatField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('NEW', 'New Policy'), ('NORM', 'Existing Policy'), ('RENEW', 'Renewal')], default='NEW', max_length=50)),
                ('premium_type', models.CharField(choices=[('BASIC', 'Basic Premium'), ('POLICY', 'Policy Holder Compensation Fund Levy'), ('STAMPD', 'Stamp Duty'), ('IPHCFLEVY', 'Add IPHCF/Levy'), ('TLEVY', 'Add T/Levy'), ('GROSS', 'Gross premium'), ('COMM', 'Commission'), ('WITH', 'Withholding Tax')], default='BASIC', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=50)),
                ('insurance_class', models.CharField(choices=[('COMM_GEN', 'Motor Commercial Insurance – GC - Comp'), ('COMM_OWN', 'Motor Commercial Insurance – Own Goods - Comprehensive'), ('COMM_OWN_TPO', 'Motor Commercial Insurance – Own Goods - T.P.O'), ('PRIV_COMP', 'Motor Private Insurance – Comprehensive'), ('PRIV_TPO', 'Motor Private Insurance – T.P.O'), ('PSV_COMP', 'Motor PSV – Comprehensive'), ('PSV_TPO', 'Motor PSV – T.P.O')], default='COMM_GEN', max_length=50)),
                ('remarks', models.TextField(blank=True, max_length=500, null=True)),
                ('additional_benefits', models.ManyToManyField(to='policy_addition.AdditionalBenefit')),
                ('additional_premiums', models.ManyToManyField(to='policies.AdditionalPremium')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor.motorpolicy')),
            ],
            options={
                'verbose_name': 'Policy Addition',
                'verbose_name_plural': 'Policy Additions',
                'db_table': 'policy_additions',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAdditionalBenefit',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('benefit', models.CharField(choices=[('COURT', 'Courtesy car'), ('EXCESS', 'Excess Protection'), ('WIND', 'Windscreen extension'), ('MED', 'Medical expenses'), ('POLITICAL', 'Political violence and Terrorism cover')], default='COURT', max_length=15)),
                ('commission_rate', models.FloatField(null=True)),
                ('minimum_amount', models.FloatField(blank=True, null=True)),
                ('history_change_reason', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), blank=True, null=True, size=None)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical additional benefit',
                'db_table': 'history_policy_additions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
