# Generated by Django 3.2.6 on 2021-12-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_addition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyaddition',
            name='value',
            field=models.FloatField(default=50000),
            preserve_default=False,
        ),
    ]
