# Generated by Django 3.2.6 on 2021-12-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_addition', '0002_policyaddition_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyaddition',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
