# Generated by Django 3.2.6 on 2021-12-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_addition', '0003_alter_policyaddition_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyaddition',
            name='insurance_class',
        ),
        migrations.RemoveField(
            model_name='policyaddition',
            name='status',
        ),
    ]
